# Generated by Django 2.1.7 on 2021-09-04 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Email')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('franchise', 'Franchisee')], default='Regular', max_length=30, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter valid contact number with country code', max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('dob', models.DateField(max_length=8, null=True, verbose_name='Date of Birth')),
                ('hq', models.CharField(choices=[('No formal education', 'No formal education'), ('Primary Education', 'Primary Education'), ('Secondary Education', 'Secondary Education'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree")], max_length=50, null=True, verbose_name='Highest Qualification')),
                ('pro_pic', models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to='profile_pictures', verbose_name='Profile Picture')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Email Verification')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('transactions', models.ManyToManyField(blank=True, to='payu.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FranchiseeOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_batch', models.CharField(max_length=10)),
                ('total_certificate', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Franchisee Owner',
                'verbose_name_plural': 'Franchisee Owners',
            },
        ),
        migrations.CreateModel(
            name='PilotCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30, verbose_name='Gender')),
                ('Dob', models.CharField(blank=True, max_length=200, verbose_name='Date of Birth')),
                ('Address', models.CharField(max_length=250)),
                ('Photo_ID_detail', models.CharField(choices=[('voter id', 'voter id '), ('Aadhar no', 'Aadhar no')], default='voter id', max_length=100, verbose_name='Photo ID Type')),
                ('Photo_ID', models.CharField(max_length=100, verbose_name='Photo ID Number')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Photo ID Image')),
                ('certificate_number', models.CharField(max_length=200, verbose_name='Certificate Number')),
                ('dateofissue', models.CharField(blank=True, default='', max_length=200, verbose_name='Date of Issue')),
                ('category', models.CharField(choices=[('Micro Category Multirotor Drone Pilot Course', 'Micro Category Multirotor Drone Pilot Course'), ('Small Category Multirotor Drone Pilot Course', 'Small Category Multirotor Drone Pilot Course'), ('Micro Category Fixedwing Drone Pilot Course', 'Micro Category Fixedwing Drone Pilot Course')], max_length=200)),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='Fee Collected')),
                ('completed', models.BooleanField(default=False, verbose_name='Form Completed')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('valid_date', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pilot Certificate',
                'verbose_name_plural': 'Pilot Certificates',
            },
        ),
        migrations.AddField(
            model_name='franchiseeowners',
            name='certificate_students',
            field=models.ManyToManyField(blank=True, null=True, to='account.PilotCertificates'),
        ),
        migrations.AddField(
            model_name='franchiseeowners',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
