# Generated by Django 2.0.2 on 2021-11-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('free', 'free'), ('Monthly', 'Monthly'), ('year', 'year')], default='Free', max_length=30)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
