# Generated by Django 2.0.2 on 2021-11-10 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('dateofaccount', models.DateTimeField(auto_now=True)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.membership')),
                ('usermembership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
