# Generated by Django 2.1.7 on 2021-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usermembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Monthly', 'Monthly'), ('Year', 'Year')], default='Free', max_length=30),
        ),
    ]
