# Generated by Django 2.1.7 on 2021-11-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211114_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='membership_type',
            new_name='membership_method',
        ),
    ]
