# Generated by Django 2.1.7 on 2021-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsportal', '0003_auto_20211119_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
