# Generated by Django 2.1.7 on 2021-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsportal', '0008_auto_20211130_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='Application_apply',
            field=models.ManyToManyField(to='jobsportal.Application'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='jobs_add',
            field=models.ManyToManyField(to='jobsportal.Job'),
        ),
    ]
