# Generated by Django 2.1.7 on 2021-11-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsportal', '0009_auto_20211130_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='Application_apply',
            field=models.ManyToManyField(blank=True, null=True, to='jobsportal.Application'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='jobs_add',
            field=models.ManyToManyField(blank=True, null=True, to='jobsportal.Job'),
        ),
    ]
