# Generated by Django 2.1.7 on 2021-12-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsportal', '0011_remove_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='jobs_add',
            field=models.ManyToManyField(blank=True, null=True, related_name='zones', to='jobsportal.Job'),
        ),
    ]
