# Generated by Django 2.1.7 on 2021-12-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsportal', '0012_auto_20211202_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='company',
            new_name='profilename',
        ),
    ]
