# Generated by Django 2.1.7 on 2021-12-07 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsportal', '0013_auto_20211204_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='allcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='jobs_add',
        ),
        migrations.AddField(
            model_name='student_apply',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsportal.allcategory'),
        ),
    ]
