# Generated by Django 2.1.7 on 2021-12-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsportal', '0015_auto_20211207_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcategory',
            name='img',
            field=models.ImageField(default='s4.jpg', upload_to=''),
        ),
    ]
