# Generated by Django 2.1.7 on 2021-06-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
