# Generated by Django 2.1.7 on 2021-06-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210605_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='description2',
        ),
    ]
