# Generated by Django 2.1.7 on 2021-06-07 04:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210605_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description3',
            field=ckeditor.fields.RichTextField(blank=True, default='product Description', null=True),
        ),
    ]
