# Generated by Django 2.1.7 on 2021-06-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_item_description3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('s', 'shirt'), ('sw', 'sport wear '), ('OW', 'Outwear')], max_length=100, null=True),
        ),
    ]
