# Generated by Django 2.1.7 on 2021-06-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_allorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
    ]
