# Generated by Django 2.1.7 on 2021-06-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payu', '0001_initial'),
        ('store', '0011_remove_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingorder',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='Invoice/'),
        ),
        migrations.AddField(
            model_name='kingorder',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payu.Transaction'),
        ),
    ]
