# Generated by Django 2.1.7 on 2021-06-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210609_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingorder',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
