# Generated by Django 2.1.7 on 2021-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210611_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='shipment',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('completed', 'completed'), ('Active', 'active')], max_length=100, null=True),
        ),
    ]
