# Generated by Django 2.1.7 on 2021-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_billingaddress_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='shipment',
        ),
        migrations.AddField(
            model_name='kingorder',
            name='shipment',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('completed', 'completed'), ('Active', 'active')], max_length=100, null=True),
        ),
    ]
