# Generated by Django 2.1.7 on 2021-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210611_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingorder',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
