# Generated by Django 2.1.7 on 2021-06-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210611_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='kingorder',
            options={'verbose_name': 'Products Order'},
        ),
    ]
