# Generated by Django 2.1.7 on 2021-06-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210612_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingorder',
            name='shipment',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Active', 'Active')], default='active', max_length=100, null=True),
        ),
    ]
