# Generated by Django 2.1.7 on 2021-06-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210612_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kingorderitems',
            options={'verbose_name': 'OrderedList'},
        ),
    ]
