# Generated by Django 2.1.7 on 2021-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210612_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description2',
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, help_text='please uploas high resolution images', null=True, upload_to=''),
        ),
    ]
