# Generated by Django 2.1.7 on 2021-06-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210614_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, help_text='please upload high resolution images', null=True, upload_to=''),
        ),
    ]
