# Generated by Django 2.1.7 on 2021-06-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210615_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name': 'Billing Addres'},
        ),
    ]
