# Generated by Django 2.1.7 on 2021-06-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20210615_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingorder',
            name='url1',
            field=models.URLField(blank=True, null=True),
        ),
    ]
