# Generated by Django 2.1.7 on 2021-06-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_kingorder_url1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kingorder',
            old_name='url1',
            new_name='Tracking_field',
        ),
    ]
