# Generated by Django 2.1.7 on 2021-06-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20210615_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name': 'Billing Address', 'verbose_name_plural': 'Billing Address'},
        ),
        migrations.AlterModelOptions(
            name='kingorderitems',
            options={'verbose_name': 'Ordered List'},
        ),
    ]
