# Generated by Django 2.1.7 on 2021-06-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20210615_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kingorder',
            options={'verbose_name': 'Ordered Products', 'verbose_name_plural': 'Ordered Products'},
        ),
    ]
