# Generated by Django 2.1.7 on 2021-06-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210615_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description3',
            new_name='description2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
