# Generated by Django 2.1.7 on 2021-06-29 18:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20210615_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kingorder',
            options={'verbose_name': 'Ordered Product', 'verbose_name_plural': 'Ordered Products'},
        ),
        migrations.AlterField(
            model_name='item',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, default='Product Description', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, help_text='Image resolution must be 600px x 600px', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='kingorder',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='store.KingOrderItems'),
        ),
    ]
