# Generated by Django 2.1.7 on 2021-01-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactinfo_traning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='url1',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='mapiframe',
            field=models.CharField(default='', max_length=250),
        ),
    ]
