# Generated by Django 2.1.7 on 2021-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210108_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='mapiframe',
            field=models.TextField(),
        ),
    ]
