# Generated by Django 2.1.7 on 2021-01-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210108_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'IId-Center'},
        ),
        migrations.AlterModelOptions(
            name='traning',
            options={'verbose_name': 'Traning-Schedule'},
        ),
        migrations.AddField(
            model_name='traning',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='type',
            field=models.CharField(choices=[('Head Office', 'head_office'), ('Partners', 'Partners'), ('Franchisee', 'Franchisee')], default='', max_length=100),
        ),
    ]
