# Generated by Django 2.1.7 on 2021-01-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210108_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traning',
            name='slug',
        ),
    ]
