# Generated by Django 2.1.7 on 2021-01-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_traning_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'IID-Location'},
        ),
    ]
