# Generated by Django 2.1.7 on 2021-01-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('app', '0008_auto_20210108_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactinfo',
            new_name='IIDLocations',
        ),
        migrations.RenameModel(
            old_name='Traning',
            new_name='TrainingSchedule',
        ),
    ]
