# Generated by Django 2.1.7 on 2021-01-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210109_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iidlocations',
            name='Phone1',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='iidlocations',
            name='Phone2',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='iidlocations',
            name='type',
            field=models.CharField(choices=[('Head_Office', 'Head Office'), ('Partners', 'Partners'), ('Franchisee', 'Franchisee')], default='Franchisee', max_length=100),
        ),
    ]
