# Generated by Django 2.1.7 on 2021-01-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210109_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iidlocations',
            name='Phone1',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='iidlocations',
            name='Phone2',
            field=models.CharField(max_length=14),
        ),
    ]
