# Generated by Django 2.1.7 on 2021-01-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210123_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCalendar',
        ),
        migrations.AddField(
            model_name='query',
            name='Location',
            field=models.CharField(max_length=20, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expiry',
            field=models.DurationField(help_text='Eg: 30 days', verbose_name='Course Expiry'),
        ),
    ]
