# Generated by Django 2.1.7 on 2021-01-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_query_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Location'),
        ),
    ]
