# Generated by Django 2.1.7 on 2021-02-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210116_1129'),
        ('app', '0016_auto_20210127_1141'),
    ]

    operations = [
    ]
