# Generated by Django 2.1.7 on 2021-02-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20210201_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webniar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=100)),
                ('tentative_speakers', models.TextField()),
                ('registration_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='query',
            name='Location',
            field=models.CharField(max_length=20, null=True, verbose_name='Location'),
        ),
    ]
