# Generated by Django 2.1.7 on 2021-02-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210201_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webniar',
            name='tentative_speakerst',
        ),
    ]
