# Generated by Django 2.1.7 on 2021-02-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_webniar_tentative_speakerst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webniar',
            new_name='Webinar',
        ),
    ]
