# Generated by Django 2.1.7 on 2021-05-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210413_1039'),
        ('app', '0023_auto_20210502_1958'),
    ]

    operations = [
    ]
