# Generated by Django 2.1.7 on 2021-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_merge_20210502_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotlist',
            name='certificate_no',
            field=models.CharField(max_length=30, verbose_name='Certificate Number'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Topic'),
        ),
    ]
