# Generated by Django 2.1.7 on 2021-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210609_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(help_text='please upload high resolution images', upload_to='Gallery/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text='please uploas high resolution images', upload_to='CourseImages/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='please upload high resolution images', null=True, upload_to='LessonThumb/'),
        ),
    ]
