# Generated by Django 2.1.7 on 2021-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210614_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text='please upload high resolution images', upload_to='CourseImages/'),
        ),
    ]
