# Generated by Django 2.1.7 on 2021-06-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210614_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text='please upload  1300*600 ', upload_to='CourseImages/'),
        ),
    ]
