# Generated by Django 2.1.7 on 2021-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210615_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(help_text='Image resolution must be 800px * 450px', upload_to='Gallery/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(help_text=' please upload  1300*600 ', upload_to='CourseImages/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='app.OrderItem'),
        ),
    ]
