# Generated by Django 2.1.7 on 2020-12-01 20:15

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(null=True)),
                ('descriptions', models.CharField(max_length=100, null=True)),
                ('datetrue', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='pls inserted', null=True)),
                ('my_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
