# Generated by Django 2.1.7 on 2020-12-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='my_image',
            new_name='CoverImage',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='datetrue',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='descriptions',
            new_name='Description',
        ),
    ]
