# Generated by Django 2.1.7 on 2020-12-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20201202_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='img',
            new_name='Img',
        ),
    ]
