# Generated by Django 2.1.7 on 2020-12-05 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20201204_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
