# Generated by Django 2.1.7 on 2020-12-16 09:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20201205_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, default='Main Blog Content', null=True),
        ),
    ]
